apiVersion: v1
kind: ReplicationController
metadata:
  name: my-nginx
spec:
  replicas: 3
  template:
    metadata:
      name: my-nginx
      labels:
        app: my-nginx
        type: front-end
    spec:
      containers:
        - name: my-nginx
          image: nginx
          ports:
            - containerPort: 80
