apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    app: my-nginx
    type: front-end
spec:
  selector:
    app: my-nginx
    type: front-end
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008
